# Generated by Django 5.1.2 on 2024-11-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="Sin título", max_length=100),
        ),
    ]
