# Generated by Django 5.1.2 on 2024-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0003_product_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cart_item",
            new_name="CartItem",
        ),
    ]
